# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-26 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyho_app', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type_message',
            field=models.IntegerField(choices=[(1, b'Admin'), (2, b'Client')], default=1, verbose_name=b'\xd0\xa2\xd0\xb8\xd0\xbf'),
        ),
    ]
