# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-27 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyho_app', '0005_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
