# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-27 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyho_app', '0008_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='comment',
            field=models.TextField(default=b''),
        ),
    ]
