# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-27 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyho_app', '0009_homework_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='answer',
            field=models.FileField(default=0, upload_to=b'answers/'),
        ),
    ]
