# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-18 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyho_app', '0010_homework_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_user',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
