# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-18 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyho_app', '0011_profile_type_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.BooleanField(default=False)),
                ('two', models.BooleanField(default=False)),
                ('three', models.BooleanField(default=False)),
                ('four', models.BooleanField(default=False)),
                ('five', models.BooleanField(default=False)),
                ('six', models.BooleanField(default=False)),
                ('seven', models.BooleanField(default=False)),
                ('eight', models.BooleanField(default=False)),
                ('nine', models.BooleanField(default=False)),
                ('ten', models.BooleanField(default=False)),
                ('eleven', models.BooleanField(default=False)),
                ('twelve', models.BooleanField(default=False)),
                ('therteen', models.BooleanField(default=False)),
                ('fourteen', models.BooleanField(default=False)),
                ('fiveteen', models.BooleanField(default=False)),
                ('sixteen', models.BooleanField(default=False)),
                ('seventeen', models.BooleanField(default=False)),
                ('eighteen', models.BooleanField(default=False)),
                ('nineteen', models.BooleanField(default=False)),
                ('twenty', models.BooleanField(default=False)),
                ('twentyone', models.BooleanField(default=False)),
                ('twentytwo', models.BooleanField(default=False)),
                ('twentythree', models.BooleanField(default=False)),
            ],
        ),
    ]
