# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-18 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyho_app', '0012_anketa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anketa',
            name='eight',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='eighteen',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='eleven',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='five',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='fiveteen',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='four',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='fourteen',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='nine',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='nineteen',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='one',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='seven',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='seventeen',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='six',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='sixteen',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='ten',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='therteen',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='three',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='twelve',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='twenty',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='twentyone',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='twentythree',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='twentytwo',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='two',
        ),
        migrations.AddField(
            model_name='anketa',
            name='answer',
            field=models.TextField(default=b'', verbose_name=b'\xd0\x9e\xd1\x82\xd0\xb2\xd0\xb5\xd1\x82'),
        ),
        migrations.AddField(
            model_name='anketa',
            name='title',
            field=models.TextField(default=b'', verbose_name=b'\xd0\x92\xd0\xbe\xd0\xbf\xd1\x80\xd0\xbe\xd1\x81'),
        ),
    ]
