# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-18 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psyho_app', '0013_auto_20190518_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anketa',
            name='answer',
        ),
    ]
