# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-18 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyho_app', '0014_remove_anketa_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.BooleanField(default=False, verbose_name=b'?')),
                ('two', models.BooleanField(default=False, verbose_name=b'?')),
                ('three', models.BooleanField(default=False, verbose_name=b'?')),
                ('four', models.BooleanField(default=False, verbose_name=b'?')),
                ('five', models.BooleanField(default=False, verbose_name=b'?')),
                ('six', models.BooleanField(default=False, verbose_name=b'?')),
                ('seven', models.BooleanField(default=False, verbose_name=b'?')),
                ('eight', models.BooleanField(default=False, verbose_name=b'?')),
                ('nine', models.BooleanField(default=False, verbose_name=b'?')),
                ('ten', models.BooleanField(default=False, verbose_name=b'?')),
                ('eleven', models.BooleanField(default=False, verbose_name=b'?')),
                ('twelve', models.BooleanField(default=False, verbose_name=b'?')),
                ('thirteen', models.BooleanField(default=False, verbose_name=b'?')),
                ('fourteen', models.BooleanField(default=False, verbose_name=b'?')),
                ('fiveteen', models.BooleanField(default=False, verbose_name=b'?')),
                ('sixteen', models.BooleanField(default=False, verbose_name=b'?')),
                ('seventeen', models.BooleanField(default=False, verbose_name=b'?')),
                ('eighteen', models.BooleanField(default=False, verbose_name=b'?')),
                ('nineteen', models.BooleanField(default=False, verbose_name=b'?')),
                ('twenty', models.BooleanField(default=False, verbose_name=b'?')),
                ('twentyone', models.BooleanField(default=False, verbose_name=b'?')),
                ('twentytwo', models.BooleanField(default=False, verbose_name=b'?')),
                ('twentythree', models.BooleanField(default=False, verbose_name=b'?')),
            ],
        ),
    ]
