# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-18 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psyho_app', '0015_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='psyhotype',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
